import time
noun1 = input("Please enter a noun: ")
noun2 = input("Please enter a noun: ")
noun3 = input("Please enter a noun: ")
adjective1 = input("Please enter an adjective: ")
noun4 = input("Please enter a noun: ")
adjective2 = input("Please enter an adjective: ")
adjective3 = input("Please enter an adjective: ")
noun5 = input("Please enter a noun: ")
pluralnoun = input("Please enter a plural noun: ")
adjective4 = input("Please enter an adjective: ")
noun6 = input("Please enter a noun: ")

print()

print("On the first day of Christmas,")
print("My",noun1," gave to me")
print("A partridge in a/an",noun2," tree.")
print("On the second",noun3," of Christmas,")
print("My",adjective1," love gave to me")
print("Two turtle doves")
print("And a/an",noun4," in a/an",adjective2," tree.")
print("On the third day of Christmas,")
print("My",adjective3," ",noun5," gave to me")
print("Three French hens,")
print("Two turtle",pluralnoun,",")
print("And a partridge in a/an",adjective4," ",noun6,".")
time.sleep(60)
