import time
noun1 = input("Please enter a noun: ")
adjective1 = input("Please enter an adjective: ")
noun2 = input("Please enter a noun: ")
food1 = input("please enter a type of food: ")
number1 = input("Please enter a number: ")
personinroom1 = input("Please enter a person in the room: ")
noun3 = input("Please enter a noun: ")
place1 = input("Please enter a place: ")
articleofclothing1 = input("Please enter a article of clothing: ")
noun4 = input("Please enter a noun: ")
verb1= input("Please enter a verb: ")
adjective2 = input("Please insert an adjective: ")
noun5 = input("Please enter a noun: ")
personinroom2 = input("Please enter a person in the room: ")
pluralnoun1 = input("Please enter a plural noun: ")
noun6 = input("Please enter a noun: ")
print("Welcome to Gamer Con 5000! We're excited to have you. Please")
print("check your",noun1," for a list of",adjective1," items you may bring")
print("inside the",noun2,".",food1," are strictly prohibited!")
print("Gaming Centers will be set up in",number1," locations, and attendees will be")
print("divided up by character. If you are dressed as",personinroom1," from",noun3,",")
print("please check in at (the)",place1,". If you are wearing")
print("a/an",articleofclothing1,", you will be denied entry unless accompanied by")
print("your",noun4,". Attendees looking to play Star",verb1," and The",adjective2,noun5," should")
print("register online. No one dressed as",personinroom2," will be allowed in the bathrooms for")
print("any reason. Please bring extra",pluralnoun1," and remember to have a/an",noun6,"!")
time.sleep(60)

