#This is my Thanksgiving MadLib
import time
pluralnoun1 = input("Please enter a plural noun: ")
adjective1 = input("Please enter an adjective: ")
animal = input("Please enter an animal: ")
noun1 = input("Please enter a noun: ")
adjective2 = input("Please enter an adjective: ")
adjective3 = input("Please enter an adjective: ")
pluralnoun2 = input("Please enter a plural noun: ")
noun2 = input("Please enter a noun: ")
adjective4 = input("Please enter an adjective: ")
noun3 = input("Please enter a noun: ")
noun4 = input("Please enter a noun: ")
adjective5 = input("Please enter an adjective: ")
noun5 = input("Please enter a noun: ")
pluralnoun3 = input("Please enter a plural noun: ")
adjective6 = input("Please enter an adjective: ")
noun6 = input("Please enter a noun: ")

print()

print("This is how I made one million",pluralnoun1,"in the stock market. It's")
print("simple. At the present time, any",adjective1,"investor with a little capital")
print("should be able to double his",pluralnoun1," in a few months. All the experts agree that we are")
print("near the end of our",animal,"market. Just recently, for instance, the American",noun1,"and")
print("Foundary Company has shown a/an",adjective2,"trend. Conditions indicate a/an",adjective3,"market")
print("for their principal product, automatic",pluralnoun2,"International Telephone and",noun2,"Company")
print("also looks",adjective4,". At the end of the last fiscal",noun3," , they were earning 10 dollars a/an",noun4,".")
print("Another",adjective5,"tip is Consolidated",noun5," . This outfit manufactures and sells electronic",pluralnoun3,"of")
print("a very",adjective6,"quality. But whatever you do, act now. Remember, prosperity is just around the",noun6,".")
time.sleep(60)
